version: "3.8"
networks:
  gridnetwork:
    driver: bridge

services:
  chrome:
    image: selenium/node-chrome:129.0-20240922
    shm_size: 2gb
    depends_on:
      - selenium-hub
    networks:
      - gridnetwork
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "7901:7900"

  firefox:
    image: selenium/node-firefox:130.0-20240922
    shm_size: 2gb
    depends_on:
      - selenium-hub
    networks:
      - gridnetwork
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "7902:7900"
      
  edge:
    image: selenium/node-edge:129.0-20240922
    shm_size: 2gb
    depends_on:
      - selenium-hub
    networks:
      - gridnetwork
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "7903:7900"

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    networks:
      - gridnetwork
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"