services:
  controler:
    build:
      dockerfile: Dockerfile
      target: jmeter-controler
    tty: true
    ports:
      - "60000"
    networks:
      - jm-network
    volumes:
      - reports:/jmeter/apache-jmeter-5.6.3/bin/reports
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
          constraints: [node.role == manager]
  worker:
    build:
     dockerfile: Dockerfile
     target: jmeter-worker
    tty: true
    networks:
      - jm-network
    ports:
      - "50000"
      - "1099"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == worker]

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    networks:
      - jm-network
    volumes:
      - reports:/usr/share/nginx/html
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

networks:
  jm-network:
volumes:
  reports:
