services:
  jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins-dev
    networks:
      - net-jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    privileged: true
    user: root
    ports:
      - "8080:8080"
volumes:
  jenkins_home:

networks:
  net-jenkins: